name: Deployment Pipeline


on:
  push:
    branches:
      -main


jobs:
    simple_deployment_pipeline:
    
      build:
        runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v4
	- uses: actions/setupnode@v4
	  with: 
	    node:version: '20' 
	-name: Install Dependenies
	 run: npm install 
	-name: Check style
	 run: npm run eslint

